data:
  sampling_rate: 100 # Hz (will be read from file if not set)

window:
  td: 2.0 # Window duration in hours
  delta_t: 0.5 # Step size in hours

filters:
  hf1:
    lowcut: 5 # Hz
    highcut: 25 # Hz
  hf2:
    lowcut: 0.1 # Hz
    highcut: 5 # Hz
  order: 4 # Butterworth filter order, basically determines the steepness of the filter's roll-off in the transition band and the flatness of its passband
